spring:
  datasource:
    password: wcdevspwd
    username: wcdevsu
    url: jdbc:postgresql://localhost:5432/wcdevsdb
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true

  security:
    oauth2:
      client:
        provider:
          cognito:
            issuerUri: http://localhost:8888/auth/realms/wcdevs
        registration:
          cognito:
            clientId: "wcdevs-core-client"
            clientName: "wcDevs core application"
            clientSecret: "857964ff-674c-4892-a31f-50a6df8c319e"
      resourceserver:
        jwt:
          issuerUri: http://localhost:8888/auth/realms/wcdevs
