spring:
  datasource:
    password: wcdevspwd
    username: wcdevsu
    url: jdbc:postgresql://localhost:5432/wcdevsdb
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8888/auth/realms/wcdevs-realm
