spring:
  # see https://docs.spring.io/spring-boot/docs/current/reference/html/features.html#features.external-config
  datasource:
    driver-class-name: ${CORE_APP_DB_DRIVER}
    url: ${CORE_APP_DB_URL}
    password: ${CORE_APP_DB_PASSWORD}
    username: ${CORE_APP_DB_USER}
  jpa:
    generate-ddl: false
    open-in-view: false
    show-sql: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        globally_quoted_identifiers: "true"
  flyway:
    connect-retries: 5
    create-schemas: true
    enabled: true
    driver-class-name: ${spring.datasource.driver-class-name}
    encoding: UTF-8
    schemas: public
    default-schema: public
    password: ${spring.datasource.password}
    user: ${spring.datasource.username}
    url: ${spring.datasource.url}
    locations: classpath:db/migration/{vendor}
  sql:
    init:
      mode: never

server:
  port: ${CORE_APP_LISTEN_PORT}

management:
  server:
    port: ${CORE_APP_MANAGEMENT_PORT}
  endpoints:
    web:
      base-path: "/manage"
  metrics:
    export:
      cloudwatch:
        enabled: false

# see https://docs.awspring.io/spring-cloud-aws/docs/2.3.2/reference/html/index.html#amazon-sdk-configuration
logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error
