spring:
  datasource:
    password: wcdevspwd
    username: wcdevsu
    url: jdbc:postgresql://localhost:5432/wcdevsdb
    driver-class-name: org.postgresql.Driver

  security:
    oauth2:
      client:
        provider:
          cognito:
            issuerUri: http://localhost:8888/auth/realms/wcdevs
        registration:
          cognito:
            clientId: "wcdevs-core-client"
            clientName: "wcDevs core application"
            clientSecret: "857964ff-674c-4892-a31f-50a6df8c319e"
      resourceserver:
        jwt:
          # see http://localhost:8888/auth/realms/wcdevs/.well-known/openid-configuration
          issuerUri: http://localhost:8888/auth/realms/wcdevs

core-app:
  allowedOrigins:
    - "*"

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql: trace
