version: "3.9"

services:

  wcdevs_db:
    image: postgres:12.8-alpine
    ports:
      - "5432:5432"
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
      replicas: 1
      resources:
        limits:
          cpus: "0.70"
          memory: "512M"
    volumes:
      - wcdevs_db_data:/var/lib/postgresql/data
    environment:
      # https://github.com/docker-library/docs/blob/master/postgres/README.md#environment-variables
      POSTGRES_PASSWORD: wcdevspwd
      POSTGRES_USER: wcdevsu
      POSTGRES_DB: wcdevsdb

  keycloak:
    image: jboss/keycloak:15.0.2
    ports:
      - "8888:8080"
    environment:
      - PORT_KEYCLOAK=8080
      - KEYCLOAK_USER=keycloak
      - KEYCLOAK_PASSWORD=keycloak
      - DB_VENDOR=h2
      - JAVA_OPTS= -Dkeycloak.migration.action=import -Dkeycloak.migration.provider=singleFile -Dkeycloak.migration.file=/tmp/wcdevs-realm.json
    volumes:
      - ./appmocks/wcdevs-realm.json:/tmp/wcdevs-realm.json

  wcdevs_app:
    image: org.wcdevs.blog:core
    ports:
      - "80:8080"
      - "82:8082"
    deploy:
      restart_policy:
        max_attempts: 5
        condition: on-failure
      replicas: 1
      resources:
        limits:
          cpus: "1"
          memory: "1024M"
    depends_on:
      - wcdevs_db
      - keycloak
    environment:
      CORE_APP_DB_URL: jdbc:postgresql://wcdevs_db:5432/wcdevsdb
      CORE_APP_DB_PASSWORD: wcdevspwd
      CORE_APP_DB_USER: wcdevsu
      CORE_APP_DB_DRIVER: org.postgresql.Driver
      CORE_APP_LISTEN_PORT: 8080
      CORE_APP_MANAGEMENT_PORT: 8082

volumes:
  wcdevs_db_data:
