version: "3.9"

services:

  wcdevs_db:
    image: postgres:13.4-alpine
    ports:
      - "5432:5432"
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 10
        delay: 7s
      replicas: 1
      resources:
        limits:
          cpus: "0.70"
          memory: "512M"
    volumes:
      - wcdevs_db_data:/var/lib/postgresql/data
    environment:
      # https://github.com/docker-library/docs/blob/master/postgres/README.md#environment-variables
      # overridden later by config by environment -- safe to use in local env
      POSTGRES_PASSWORD: wcdevspwd
      POSTGRES_USER: wcdevsu
      POSTGRES_DB: wcdevsdb

  wcdevs_app:
    image: lealceldeiro/com.wcdevs.blog:core-0.0.1
    ports:
      - "80:8080"
    deploy:
      restart_policy:
        max_attempts: 10
        condition: on-failure
        delay: 8s
      replicas: 1
      resources:
        limits:
          cpus: "0.70"
          memory: "512M"
    depends_on:
      - wcdevs_db
    environment:
      APP_DB_URL: jdbc:postgresql://wcdevs_db:5432/wcdevsdb
      APP_DB_PASSWORD: wcdevspwd
      APP_DB_USER: wcdevsu
      APP_DB_DRIVER: org.postgresql.Driver

volumes:
  wcdevs_db_data:
