version: "3.9"

services:

  wcdevs_db:
    image: postgres:12.8-alpine
    ports:
      - "5432:5432"
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
      replicas: 1
      resources:
        limits:
          cpus: "0.70"
          memory: "512M"
    volumes:
      - wcdevs_db_data:/var/lib/postgresql/data
    environment:
      # https://github.com/docker-library/docs/blob/master/postgres/README.md#environment-variables
      POSTGRES_PASSWORD: wcdevspwd
      POSTGRES_USER: wcdevsu
      POSTGRES_DB: wcdevsdb

  keycloak:
    # if macOS, use sleighzy/keycloak:15.0.2-arm64 instead of jboss/keycloak:15.0.2
    # image: sleighzy/keycloak:15.0.2-arm64
    image: jboss/keycloak:15.0.2
    ports:
      - "8888:8080"
    environment:
      - PORT_KEYCLOAK=8080
      - KEYCLOAK_USER=keycloak
      - KEYCLOAK_PASSWORD=keycloak
      - DB_VENDOR=h2
      - JAVA_OPTS= -Dkeycloak.migration.action=import -Dkeycloak.migration.provider=singleFile -Dkeycloak.migration.file=/tmp/wcdevs-realm.json
    volumes:
      - ./appmocks/wcdevs-realm.json:/tmp/wcdevs-realm.json

  # another keycloak instance to use while running the whole stack -- the "keycloak" service cannot
  # be re-used because the mock metadata contains some urls which depends on the docker-compose
  # service name, and it would conflict with the "keycloak" service used for debugging purposes
  keycloak.rt:
    # if macOS, use sleighzy/keycloak:15.0.2-arm64 instead of jboss/keycloak:15.0.2
    # image: sleighzy/keycloak:15.0.2-arm64
    image: jboss/keycloak:15.0.2
    environment:
      - PORT_KEYCLOAK=8080
      - KEYCLOAK_USER=keycloak
      - KEYCLOAK_PASSWORD=keycloak
      - DB_VENDOR=h2
      - JAVA_OPTS= -Dkeycloak.migration.action=import -Dkeycloak.migration.provider=singleFile -Dkeycloak.migration.file=/tmp/wcdevs-realm.json
    volumes:
      - ./appmocks/runtime-wcdevs-realm.json:/tmp/wcdevs-realm.json

  wcdevs_app:
    image: org.wcdevs.blog:core
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:8080"
      - "82:8082"
    deploy:
      restart_policy:
        max_attempts: 5
        condition: on-failure
      replicas: 1
      resources:
        limits:
          cpus: "1"
          memory: "1024M"
    depends_on:
      - wcdevs_db
      - keycloak.rt
    environment:
      SPRING_PROFILES_INCLUDE: local
      SPRING_DATASOURCE_URL: jdbc:postgresql://wcdevs_db:5432/wcdevsdb
      SPRING_DATASOURCE_DRIVERCLASSNAME: org.postgresql.Driver
      SPRING_DATASOURCE_USERNAME: wcdevsu
      SPRING_DATASOURCE_PASSWORD: wcdevspwd
      SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_COGNITO_ISSUERURI: http://keycloak.rt:8080/auth/realms/wcdevs
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUERURI: http://keycloak.rt:8080/auth/realms/wcdevs
      AWS_REGION: eu-central-1

volumes:
  wcdevs_db_data:
