version: "3.9"

services:

  wcdevs_db:
    image: postgres:12.8-alpine
    ports:
      - "5432:5432"
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
      replicas: 1
      resources:
        limits:
          cpus: "0.70"
          memory: "512M"
    volumes:
      - wcdevs_db_data:/var/lib/postgresql/data
    environment:
      # https://github.com/docker-library/docs/blob/master/postgres/README.md#environment-variables
      POSTGRES_PASSWORD: wcdevspwd
      POSTGRES_USER: wcdevsu
      POSTGRES_DB: wcdevsdb

  keycloak.service:
    image: jboss/keycloak:15.0.2
    ports:
      - "8888:8888"
    environment:
      - KEYCLOAK_USER=keycloak
      - KEYCLOAK_PASSWORD=keycloak
      - DB_VENDOR=h2
      - JAVA_OPTS= -Djboss.http.port=8888 -Dkeycloak.migration.action=import -Dkeycloak.migration.provider=singleFile -Dkeycloak.migration.file=/tmp/wcdevs-realm.json
    volumes:
      - ./appmocks/wcdevs-realm.json:/tmp/wcdevs-realm.json

  wcdevs_app:
    image: org.wcdevs.blog:core
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:8080"
      - "82:8082"
    deploy:
      restart_policy:
        max_attempts: 5
        condition: on-failure
      replicas: 1
      resources:
        limits:
          cpus: "1"
          memory: "1024M"
    depends_on:
      - wcdevs_db
      - keycloak.service
    environment:
      SPRING_PROFILES_INCLUDE: local
      SPRING_DATASOURCE_URL: jdbc:postgresql://wcdevs_db:5432/wcdevsdb
      SPRING_DATASOURCE_DRIVERCLASSNAME: org.postgresql.Driver
      SPRING_DATASOURCE_USERNAME: wcdevsu
      SPRING_DATASOURCE_PASSWORD: wcdevspwd
      # 8888: internal port exposed from WildFly server from service "keycloak.service"
      SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_COGNITO_ISSUERURI: http://keycloak.service:8888/auth/realms/wcdevs
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUERURI: http://keycloak.service:8888/auth/realms/wcdevs

volumes:
  wcdevs_db_data:
