spring:
  # configured using https://docs.spring.io/spring-boot/docs/current/reference/html/features.html#features.external-config
  datasource:
    driver-class-name: org.postgresql.Driver
    password: ${POSTGRES_PASSWORD}
    username: ${POSTGRES_USER}
    url: jdbc:postgresql://localhost:5432/${POSTGRES_DB}
  jpa:
    generate-ddl: false
    open-in-view: false
    show-sql: false
    hibernate:
      ddl-auto: validate
  flyway:
    connect-retries: 5
    create-schemas: true
    enabled: true
    driver-class-name: ${spring.datasource.driver-class-name}
    encoding: UTF-8
    schemas: public
    default-schema: public
    password: ${spring.datasource.password}
    user: ${spring.datasource.username}
    url: ${spring.datasource.url}
    locations: classpath:db/migration/{vendor}
  sql:
    init:
      mode: never

server:
  port: 8080
