name: Build and Publish

on:
  push:
    paths:
      - '.mvn/**'
      - 'common/src/**'
      - 'common/pom.xml'
      - 'persistence/src/**'
      - 'persistence/pom.xml'
      - 'rest/src/**'
      - 'rest/pom.xml'
      - 'pom.xml'
      - 'docker-compose.yml'
      - 'Dockerfile'
      - 'mvnw'
      - 'mvnw.cmd'
      - '.github/workflows/build-and-publish.yml'
  pull_request:
    paths:
      - '.mvn/**'
      - 'common/src/**'
      - 'common/pom.xml'
      - 'persistence/src/**'
      - 'persistence/pom.xml'
      - 'rest/src/**'
      - 'rest/pom.xml'
      - 'pom.xml'
      - 'docker-compose.yml'
      - 'Dockerfile'
      - 'mvnw'
      - 'mvnw.cmd'
      - '.github/workflows/build-and-publish.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    # https://docs.github.com/en/actions/learn-github-actions/expressions#endswith
    # https://docs.github.com/en/actions/learn-github-actions/workflow-commands-for-github-actions#setting-an-environment-variable
    steps:
      - name: Set env to staging
        if: ${{ startsWith(github.ref, '/develop') && endsWith(github.ref, '/develop') }}
        run: |
          echo "DEPLOY_ENV=staging" >> $GITHUB_ENV

      - name: Set env to prod
        if: ${{ startsWith(github.ref, '/main') && endsWith(github.ref, '/main') }}
        run: |
          echo "DEPLOY_ENV=prod" >> $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven

      - name: Build with Maven
        # -B,--batch-mode
        # see mvn --help for more info
        run: mvn -B clean verify package --file pom.xml

      - name: Codecov
        uses: codecov/codecov-action@v2
        with:
          files: ./persistence/target/site/jacoco/jacoco.xml,./common/target/site/jacoco/jacoco.xml,./rest/target/site/jacoco/jacoco.xml
          fail_ci_if_error: true
          verbose: true

      - name: Create Docker image tag
        if: ${{ env.DEPLOY_ENV == 'staging' || env.DEPLOY_ENV == 'prod' }}
        id: dockerImageTag
        run: echo "::set-output name=tag::${DEPLOY_ENV}-$(date +'%Y%m%d%H%M%S')-${GITHUB_SHA}"

      - name: Publish Docker image to ECR registry
        if: ${{ env.DEPLOY_ENV == 'staging' || env.DEPLOY_ENV == 'prod' }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
          DOCKER_IMAGE_TAG: ${{ steps.dockerImageTag.outputs.tag }}
          ECR_REPO_NAME: ${{ secrets.ECR_REPO_NAME }}
        run: |
          echo OS Information:
          lsb_release -sidrc
          echo Docker Information:
          docker -v
          docker build -t orgwcdevsblogcore .
          echo Images:
          docker image ls
          echo "AWS CLI Info: $(aws --version)"
          aws ecr get-login-password --region ${AWS_DEFAULT_REGION} | docker login -u AWS --password-stdin ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com
          docker tag orgwcdevsblogcore ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/${ECR_REPO_NAME}:${DOCKER_IMAGE_TAG}
          docker push ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/${ECR_REPO_NAME}:${DOCKER_IMAGE_TAG}

      - name: Send Deployment event to queue
        if: ${{ env.DEPLOY_ENV == 'staging' || env.DEPLOY_ENV == 'prod' }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
          DOCKER_IMAGE_TAG: ${{ steps.dockerImageTag.outputs.tag }}
          # see https://github.com/lealceldeiro/org.wcdevs.blog.awsdeployer/blob/main/deployment-sequencer-lambda/src/index.ts#L65
        run: |
          export EVENT_PAYLOAD="{\"commitSha\": \"$GITHUB_SHA\", \"ref\": \"main\", \"owner\": \"lealceldeiro\", \"repo\": \"org.wcdevs.blog.awsdeployer\", \"workflowId\": \"core-app-deployment.yml\", \"environmentName\": \"$DEPLOY_ENV\", \"applicationName\": \"core\", \"dockerImageTag\": \"$DOCKER_IMAGE_TAG\"}"
          aws sqs send-message \
            --queue-url=https://sqs.${AWS_DEFAULT_REGION}.amazonaws.com/${AWS_ACCOUNT_ID}/$DEPLOY_ENV-core-depQueue.fifo \
            --message-group-id default \
            --message-deduplication-id $GITHUB_SHA \
            --message-body "$EVENT_PAYLOAD"
